root: .

structure:
  readme: README.md
  summary: SUMMARY.md

title: gokanlogic
description: [![Version](https://img.shields.io/badge/version-1.0.1-blue.svg)](https://github.com/gitrdm/gokanlogic/releases)

gitbook: ">=3.2.0"

plugins:
  - search
  - sharing
  - fontsettings
  - theme-default

pluginsConfig:
  sharing:
    github: true
    facebook: false
    twitter: false
    weibo: false
    instapaper: false
    vk: false
    all: ["github"]
  
  fontsettings:
    theme: "white"
    family: "sans"
    size: 2

pdf:
  pageNumbers: true
  fontSize: 12
  fontFamily: "Arial"
  paperSize: "a4"
  margin:
    right: 62
    left: 62
    top: 56
    bottom: 56
